#!/usr/bin/env bash
# Checks for dependencies specification upgrades
#
#     (e.g., to the latest compatible configuration)  (after bootstrapping)
#
#
#   Usage:  upgrade-dependencies-spec-check [OPTION]... [ARGUMENT]...
#
#     See --help option output
#
#
#   See bootstrap

description='Checks for dependencies specification upgrades  (after bootstrapping)'
arguments_optional_multi=(ARGUMENT)

. "$(dirname -- "$0")/.bashrc"  # Bootstrap in this script's directory

log_command ./requirements_txt_checker.sh "$@"
# https://govready-q.readthedocs.io/en/latest/testing-for-govready-q/supply-chain-and-dependency-management.html?highlight=requirements_txt_checker.sh#supply-chain-and-dependency-management
